#!/usr/bin/env node
/**
 * Writes SDK build-time origin constants:
 *   DEVORA_SDK_API_ORIGIN        the Devora API (Convex HTTP actions) origin
 *   DEVORA_SDK_DASHBOARD_ORIGIN  the Devora dashboard the browser SDK accepts
 *                                exchange verifiers from (default: production)
 * Run automatically before SDK builds and type checks.
 */
import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs"
import { dirname, join } from "node:path"
import { fileURLToPath } from "node:url"

const sdksRoot = join(dirname(fileURLToPath(import.meta.url)), "..")
const envFile = join(sdksRoot, ".env")
const tsOutFile = join(sdksRoot, "core/src/constants/api-url.gen.ts")
const pythonOutFile = join(sdksRoot, "python/src/devora_sdk/api_url_gen.py")
const envVarName = "DEVORA_SDK_API_ORIGIN"

function loadDotEnv(filePath) {
	if (!existsSync(filePath)) return
	for (const line of readFileSync(filePath, "utf8").split("\n")) {
		const trimmed = line.trim()
		if (!trimmed || trimmed.startsWith("#")) continue
		const idx = trimmed.indexOf("=")
		if (idx === -1) continue
		const key = trimmed.slice(0, idx).trim()
		const value = trimmed
			.slice(idx + 1)
			.trim()
			.replace(/^["']|["']$/g, "")
		if (!(key in process.env)) {
			process.env[key] = value
		}
	}
}

// A release build must name its origin explicitly: never fall back to a
// developer's local .env (which points at a development deployment).
if (process.env.CI !== "true") loadDotEnv(envFile)

const apiUrl = process.env[envVarName]?.trim()
if (!apiUrl) {
	console.error(
		`${envVarName} is required to build Devora SDKs.\n` +
			`  Local: set ${envVarName}\n` +
			`  CI: set ${envVarName} in the workflow (local .env files are ignored when CI=true)`
	)
	process.exit(1)
}

let parsed
try {
	parsed = new URL(apiUrl)
} catch {
	console.error(`${envVarName} is not a valid URL: ${apiUrl}`)
	process.exit(1)
}

if (parsed.protocol !== "https:") {
	console.error(`${envVarName} must use https: (got ${parsed.protocol})`)
	process.exit(1)
}

if (parsed.username || parsed.password || parsed.pathname !== "/" || parsed.search || parsed.hash) {
	console.error(
		`${envVarName} must be an origin only, for example https://YOUR_DEPLOYMENT.convex.site`
	)
	process.exit(1)
}

const origin = parsed.origin.replace(/\/$/, "")

// The one dashboard whose tab may hand an exchange verifier to the browser SDK.
// Production builds trust only the production dashboard; staging builds set
// this to the staging dashboard. Plain http is allowed only for loopback.
const dashboardVarName = "DEVORA_SDK_DASHBOARD_ORIGIN"
const dashboardValue = process.env[dashboardVarName]?.trim() || "https://app.devora.sh"
let dashboard
try {
	dashboard = new URL(dashboardValue)
} catch {
	console.error(`${dashboardVarName} is not a valid URL: ${dashboardValue}`)
	process.exit(1)
}
const loopback = ["localhost", "127.0.0.1", "[::1]"].includes(dashboard.hostname)
if (
	!(dashboard.protocol === "https:" || (loopback && dashboard.protocol === "http:")) ||
	dashboard.username ||
	dashboard.password ||
	dashboard.pathname !== "/" ||
	dashboard.search ||
	dashboard.hash
) {
	console.error(
		`${dashboardVarName} must be an https origin (http only for localhost), for example https://app.devora.sh`
	)
	process.exit(1)
}
const dashboardOrigin = dashboard.origin

const tsContents = `/** Generated by scripts/generate-api-url.mjs - do not edit */
export const DEVORA_API_ORIGIN = ${JSON.stringify(origin)} as const
export const DEVORA_DASHBOARD_ORIGIN = ${JSON.stringify(dashboardOrigin)} as const
`
const pythonContents = `# Generated by scripts/generate-api-url.mjs - do not edit
DEVORA_API_ORIGIN = ${JSON.stringify(origin)}
`

for (const filePath of [tsOutFile, pythonOutFile]) {
	mkdirSync(dirname(filePath), { recursive: true })
}

writeFileSync(tsOutFile, tsContents)
writeFileSync(pythonOutFile, pythonContents)
console.log(`Wrote SDK origin constants (API ${origin}, dashboard ${dashboardOrigin})`)
